language: python

python:
- 2.7
- 3.4
- 3.5

install:
- pip install -r requirements-dev.txt
- pip install .
- pip install coveralls

deploy:
  provider: pypi
  user: dbarroso
  password:
    secure: ZGBARRS8bPy9CBunqa4C7l6ahoz3lQSRZX7fde76J+XLAziwrLwLZeSXL1PWWEm7WFvQzxPoGUGDsX6JvG5S6yKJRS76+hBlPINrrYcNJzMmNa4kOJJvPUplYZMClbqDbHNqUCdRcrrSwzcLz8lhli3Q6WuI5OZV3OFIvT5oBjUjzz9Toj8xOMCar3dH5wxcf3cTRBM1kIbRRPKC4ggPyj55QRy2Z8ridEdb8tVcpuFSbePRZYpdhZH2pYifyc9ybKkmCllWCNgVTpnpf3BNcUhuGCUq73zOCQp35gHe7xhBgjdfjIyK4EMNzYU7T3WtLcMsmmWgmnbCQtcmkPYi8ra6taXlcbu89ngs7b9+G5WZJgc5i2fW79LsUqqwjG1S3BQAIj6lfyvOoC7P/VaAFpqCm9vPM3tbWDQ4Ft9xvV4xjmeRZhy01uMkEdTPMp4eB+Qgound/++Smig/MrkOKj32cfDcVLbJzMmN4IzX17rAumgZFxEGmf7xNaUs42yazh94M+Fl5bGCSHkOD0eGDYBhX7yRatyD76IXflAP63436ptCRcR4h1JgtXOqm1j+7C9pkvruGgKIwttABE5NsJD+rNfcG2gGC10ktM1LlI/U5e/UaiGCxZ+qkMPXJEuXDPBbT5wGrrgizhDVLfTg0pF7RuGDfWzBq0sLPb2REOI=
  on:
    tags: true
    branch: master

script:
- py.test --cov-report= --cov=napalm_panos test/
- pylama .

after_success:
   - if [ $TRAVIS_TAG ]; then curl -X POST https://readthedocs.org/build/napalm; fi
